#强退pod测试通知: kubectl delete pod --force --grace-period 0 pod-name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notify
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notify
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notify
subjects:
  - kind: ServiceAccount
    name: notify
    namespace: kube-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tg-body
  namespace: kube-system
data:
  content: '{
    "chat_id": "370526622",
    "parse_mode": "MarkdownV2",
    "text": "*notify通知* \n时间: `{{ .LastTimestamp }}` \n类型: `{{ .Type }}` \nkind: `{{ .InvolvedObject.Kind }}` \n原因: `{{ .Reason }}` \n详情:```text {{ .Message }}```"
  }'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-deploy
  namespace: kube-system
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: notify-container
  template:
    metadata:
      name: notify-deploy
      labels:
        app: notify-container
      annotations:
        changeRollingUpdate: ${K8S_NOTIFY}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: notify
      priorityClassName: system-node-critical
      containers:
        - name: notify-container
          image: registry.aliyuncs.com/acs/kube-eventer:v1.2.7-ca03be0-aliyun
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: timezone
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: notify-tg-token
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            - "--sink=webhook:https://api.telegram.org/bot$TOKEN/sendMessage?level=Warning&custom_body_configmap=tg-body&custom_body_configmap_namespace=kube-system&header=Content-Type=application/json&method=POST"
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 500m
