# https://github.com/RayWangQvQ/BiliBiliToolPro
# https://github.com/shufflewzc/faker2
# https://github.com/6dylan6/jdpro

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ql-sts
spec:
  serviceName: ql-svc
  replicas: 1
  minReadySeconds: 5
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ql-container
  volumeClaimTemplates:
    - metadata:
        name: ql-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      labels:
        app: ql-container
    spec:
      restartPolicy: Always
      priorityClassName: low-pc
      terminationGracePeriodSeconds: 10
      containers:
        - name: ql-container
          image: ghcr.io/whyour/qinglong:2.16
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          ports:
            - name: cp
              containerPort: 5700
          env:
            - name: TZ
              value: Asia/Shanghai
              optional: true
          volumeMounts:
            - name: ql-data
              mountPath: /ql/data
          command:
            - /bin/sh
            - -c
            - |
              #配置从IP链排除的ip
              FILE="/etc/nginx/conf.d/ip.conf" && wget -q -O "$FILE" "https://raw.githubusercontent.com/twbworld/docker/main/conf/nginx/conf.d/common/ip.conf" || wget -q -O "$FILE" "https://cdn.jsdelivr.net/gh/twbworld/docker@main/conf/nginx/conf.d/common/ip.conf" || wget -q -O "$FILE" "https://gcore.jsdelivr.net/gh/twbworld/docker@main/conf/nginx/conf.d/common/ip.conf" || rm -f "$FILE"
              ./docker/docker-entrypoint.sh
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            httpGet:
              scheme: HTTP
              port: cp
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            exec:
              command: ["curl", "-sf", "http://127.0.0.1:5400/api/health"]
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 1

---
apiVersion: v1
kind: Service
metadata:
  name: ql-svc
spec:
  selector:
    app: ql-container
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
    - name: sp
      port: 5700
