name: main
on:
  workflow_dispatch: #github页面手动触发
  push:
    branches:
      - main
    paths:
      - 'config/proxy-cm.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'config/proxy-cm.yaml'

jobs:

  review:
    uses: ./.github/workflows/ci.yaml
    with:
      continue-on-error: false

  cd:
    needs: review
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: pull-repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ vars.PORT }}
          script: |
            set -x
            repo_name="${{ github.repository }}"
            repo_name=${repo_name#*/}
            repo_name=${repo_name#*/}
            cd /var/www/$repo_name/
            git checkout -- .
            git clean -df
            git checkout main
            git fetch origin main
            git reset --hard origin/main
            kubectl apply -f config/proxy-cm.yaml
            name="proxy-handle"
            job="$(kubectl get job -o=custom-columns=NAME:.metadata.name --no-headers | grep $name)"
            if [ -n "$job" ]; then
              echo $job |xargs kubectl delete job
            fi
            kubectl create job --from=cronjob/$name $name
